DROP TABLE IF EXISTS favorites;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS match_history;
DROP TABLE IF EXISTS rosters;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS teams;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  full_name TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS teams (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  sport TEXT NOT NULL,
  league TEXT NOT NULL,
  home_stadium TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS players (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  power INTEGER NOT NULL CHECK (power BETWEEN 1 AND 100),
  consistency INTEGER NOT NULL CHECK (consistency BETWEEN 1 AND 100),
  speed INTEGER NOT NULL CHECK (speed BETWEEN 1 AND 100),
  experience INTEGER NOT NULL CHECK (experience BETWEEN 1 AND 100),
  stamina INTEGER NOT NULL CHECK (stamina BETWEEN 1 AND 100),
  auction_price NUMERIC(12,2) NOT NULL,
  injured BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rosters (
  team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  is_star BOOLEAN NOT NULL DEFAULT FALSE,
  acquired_price NUMERIC(12,2) NOT NULL,
  acquired_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (team_id, player_id)
);

CREATE TABLE IF NOT EXISTS match_history (
  id SERIAL PRIMARY KEY,
  team_a INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  team_b INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  score_a INTEGER NOT NULL,
  score_b INTEGER NOT NULL,
  match_date TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS matches (
  id SERIAL PRIMARY KEY,
  sport TEXT NOT NULL,
  league TEXT NOT NULL,
  home_team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  away_team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  kickoff_time TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS favorites (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, match_id)
);
